# Set up Wordpress for KR47
#
# TODO: Come back and fix that password, use ansible-vault
# ...and idiot, I'm storing it in github, too?
# ...can you imagine if Keegan saw this?
# ...seriously though, once I get this to work, I'll come back and fix it. :)

---
- hosts: kr47host
  vars:
    - db_dbname:  kr47_wordpress
    - db_username:  krwordpress
    - db_password:  wordpress47
    - server_mysql_username: root
    - server_mysql_password: ""  # get this actual info from KeePass
    - wordpress_instance_name: "kr47films"
    - wordpress_install_path: "/var/www/{{ wordpress_instance_name }}"
    - wordpress_site_url: "kr47films.com"
    - wordpress_server_alias: "www.kr47films.com"
    - ftp_user: ""   # get this actual info from KeePass
    - ftp_pass: ""  # get this actual info from KeePass
    - ftp_crypt: ""  # get this actual info from KeePass
    # python -c 'import crypt; print crypt.crypt()' # get this actual info from KeePass

  remote_user: mitnick
  roles:
    - role: server_setup
    - role: wp_db_setup
    - role: wordpress
    - role: wp_ftp_user
    - role: echo_variables
