---
- hosts: meta-wordpress
  vars:
    - db_dbname:  wordpress
    - db_username:  wordpress
    - db_password:  123wordpress321
    - server_mysql_username: root
    - server_mysql_password: root
    - wordpress_instance_name: wordpress
    - wordpress_install_path: "/var/www/{{ wordpress_instance_name }}"

  remote_user: mitnick
  pre_tasks:
     #- name: Pre Task 1
     #  shell: echo 'I":" Beginning to install meta-wordpress...'
  roles:
#    - mitnick
#    - system
#    - server_setup
#    - role: geerlingguy.mysql
#      become: yes
#    - role: geerlingguy.apache
#    - role: geerlingguy.php
#      php_packages:
#        - libapache2-mod-php7.0
#    - role: php_phpinfo
#    - role: geerlingguy.php-mysql
#    - role: wp_db_setup
#    - role: wordpress
#    - role: wp_ftp_user
  post_tasks:
     #- name: Post Task 1
     #  shell: echo 'I":" Beginning to install  meta-wordpress...'
