# Set up Wordpress for KR47
#
---
- hosts: kr47host
  vars:
    - db_dbname:  kr47_wordpress
    - db_username:  krwordpress
    - db_password:  wordpress47
  roles:
    - role: wp_db_setup
    - role: echo_variables
