# Ansible nginx tutorial here: https://serversforhackers.com/an-ansible-tutorial
---
- hosts: servers
  vars:
   - docroot: /var/www/solr.kr47.net/public
  tasks:
   - name: Install Nginx
     apt: pkg=nginx state=installed update_cache=true
     register: nginxinstalled
     notify:
      - Start Nginx
   - name: Create Web Root
     when: nginxinstalled|success
     file: dest="{{ docroot }}" mode=775 state=directory owner=www-data group=www-data
     notify:
      - Reload Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started
   - name: Reload Nginx
     service: name=nginx state=reloaded



