# I like to use the alias "psg" (ps ax |grep) to grep processes for something
# just out of habit.  Not sure if this should be a play or a role or something else?
---
- name: Set Mitnick's .bashrc Path
  set_fact: remote_file_path=/home/mitnick/.bashrc

- name: Create Mitnick's .bashrc file
  file: path="{{ remote_file_path }}" state=touch

# Check the remote file...
- stat: path="{{ remote_file_path }}"
  register: file_path

# Write my psg command in there...
- set_fact: file_content="alias psg='ps ax|grep'"

# If file exists, copy the content into the remote file.
- copy: content="{{ file_content }}" dest="{{ remote_file_path }}"
  when: file_path.stat.exists == true


