---
# Commented this out, because this doesn't actually do anything!!
#- name: Add SOLR Data Files to Turkey Index
#  copy: src="files/" dest="/var/solr/data/files/data/jkb" owner=solr group=solr

- name: Replace Turkey Core solrconfig.xml with our solrconfig.xml
  copy: src="turkey/config/solrconfig.xml" dest="/var/solr/data/turkey/conf/solrconfig.xml" owner=solr group=solr

- name: Replace Turkey Core schema.xml with our schema.xml
  copy: src="turkey/config/schema.xml" dest="/var/solr/data/turkey/conf/schema.xml" owner=solr group=solr

- name: Delete the managed-schema file from Turkey Core
  file:
    path: /var/solr/data/turkey/conf/managed-schema
    state: absent

########################################################################################################################
# Productcore Info:
- name: Replace Productcore solrconfig.xml with our solrconfig.xml
  copy: src="productcore/config/solrconfig.xml" dest="/var/solr/data/productcore/conf/solrconfig.xml" owner=solr group=solr

- name: Replace Productcore schema.xml with our schema.xml
  copy: src="productcore/config/schema.xml" dest="/var/solr/data/productcore/conf/schema.xml" owner=solr group=solr

- name: Delete the managed-schema file from Productcore
  file:
    path: /var/solr/data/productcore/conf/managed-schema
    state: absent