---
#  vars:
#    # created with:
#    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
#    password: $1$MRM346e0$zOKl9L60Tvw8p3eD867lf/
- name: Create WP FTP User
  user: name="{{ ftp_user }}" password={{ ftp_crypt }}/ state=present groups=www-data
# Need to Hook this up with Ansible Vault

- name: Files and Permissions to www-data Group
  file: path=/var/www/{{ wordpress_instance_name }} group=www-data recurse=yes mode="g+rw"

- name: Update WordPress config file with FTP info
  lineinfile:
    dest=/var/www/{{ wordpress_instance_name }}/wp-config.php
    line="{{ item.line }}"
    state=present
    insertbefore='That\'s all, stop editing! Happy blogging'
  with_items:
    - {'line': "define( 'FTP_USER', '{{ ftp_user }}' );"}
    - {'line': "define( 'FTP_PASS', '{{ ftp_pass }}' );"}
    - {'line': "define( 'FTP_HOST', '{{ wordpress_site_url }}:22' );"}
    - {'line': "define( 'FS_METHOD', 'ssh2' );"}
    - {'line': "define('FTP_BASE', '/var/www/{{ wordpress_instance_name }}/');"}
    - {'line': "define('FTP_PLUGIN_DIR', '/var/www/{{ wordpress_instance_name}}/wp-content/plugins/');"}
    - {'line': "define('FTP_CONTENT_DIR', '/var/www/{{ wordpress_instance_name}}/wp-content/');"}

  become: yes

